---
- name: Restore playbook.yml
  hosts: all
  vars:
    packages:
      - httpd
      - mariadb-server
      - php
      - mutt

  tasks:
    - name: 1) 패키지 삭제
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: absent
