---
- name: Restore_playbook.yml
  hosts: all
  vars:
    firewall: firewalld
  vars_files:
    - vars/main.yml
  tasks:
    ###############################################
    # (조건) 최대한 기존의 변수들을 활용하여 작업을 진행한다.
    # (주의) 사용자 정의 팩트를 가장 마지막에 지우도록 설정한다.
    # 복원 계획
    #   - 방화벽 포트 제거 - http
    #   - 서비스 종료 - firewalld, mariadb, httpd
    #   - 서비스 설정 삭제 - /var/www/html/index.html
    #   - 패키지 삭제 - mariadb-server, httpd
    #   - 사용자 정의 팩트 삭제 - /etc/ansible/facts.d
    ###############################################
    - name: 1. 방화벽 포트 제거
      ansible.posix.firewalld:
        service: "{{ fw_port }}"
        permanent: true
        immediate: true
        state: disabled

    - name: 2. 서비스 종료
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - "{{ firewall }}"
        - "{{ ansible_local.custom.services.db_service }}"
        - "{{ ansible_local.custom.services.web_service }}"

    - name: 3. 서비스 설정 삭제
      ansible.builtin.file:
        path: "{{ web_root }}/index.html"
        state: absent

    - name: 4. 패키지 삭제 - mariadb-server, httpd
      ansible.builtin.dnf:
        name:
          - "{{ ansible_local.custom.packages.db_package }}"
          - "{{ ansible_local.custom.packages.web_package }}"
        state: absent

    - name: 5. 사용자 정의 팩트 삭제 - /etc/ansible/facts.d
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: absent

