---
- name: Create Web File
  ansible.builtin.copy:
    content: |
      <pre>
      HOSTNAME: "{{ ansible_hostname }}"
      IP: "{{ ansible_default_ipv4.address }}"
      </pre>
    dest: "{{ file }}"
    mode: '0644'