---
- name: Setting WebServer
  hosts: webservers
  gather_facts: true
  tasks:
    ###############################################
    # Play 01: 전제 조건 = CentOS
    # 1) 웹서버 패키지 설치 및 서비스 기동 - include_tasks
    #  - 웹 서버 설치 밎 기동 (tasks/web.yml)
    #  - 웹 설정(tasks/placeholder.yml)
    # 2) 방화벽 패키지 설치 및 서비스 기동, 포트 등록 - import_tasks
    #  - 방화벽 패키지, 기동, 포트 등록(tasks/fw.yml)
    # 3) 웹서버 설정(/var/www/html/index.html) - import_tasks
    # Play 02:
    # 4) 웹요청 - import_playbook
    ###############################################
    - name: CentOS 9 배포판 점검
      ansible.builtin.fail:
        msg: CentOS 9 배포판이 아닙니다.
      when:
        - ansible_distribution != "CentOS"
        - ansible_distribution_major_version != "9"

    - name: 1) 웹 서버 설치 밎 기동 (tasks/web.yml)
      ansible.builtin.include_tasks: tasks/web.yml
      vars:
        pkgs:
          - httpd
          - mod_ssl
        svc: httpd

    - name: 1) 웹 서버 설정(tasks/placeholder.yml)
      ansible.builtin.include_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html

    - name: 2) 방화벽 패키지, 기동, 포트 등록(tasks/fw.yml)
      ansible.builtin.import_tasks: tasks/fw.yml
      vars:
        pkgs:
          - firewalld
        svc: firewalld
        fw_svcs:
          - http
          - https

- name: Setup Web Request
  ansible.builtin.import_playbook: plays/test.yml
  vars:
    url: 'http://ansible1.example.com/'
    