---
- name: 1. DB 서비스 기동 - 반복문 테스트
  hosts: database_prod
  vars:
    db_packages:
      - mariadb
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb

  tasks:
    ############################
    # 1) 패키지 설치 - mariadb-server, python3-PyMySQL
    # 2) 서비스 기동 - mariadb
    ############################

    - name: 1) 패키지 설치 - mariadb-server, python3-PyMySQL
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ db_packages }}"
      # when: ansible_distribution == "CentOS"
      when: ansible_distribution == "RedHat"
      
    - name: 2) 서비스 기동 - mariadb
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: started
        enabled: true
