---
- name: Restore playbook.yml
  hosts: all
  vars:
    db_packages:
      - mariadb
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
  tasks:
    - name: 1) 서비스 종료 - mariadb
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: stopped
        enabled: false

    - name: 2) 패키지 삭제 - mariadb-server, python3-PyMySQL
      ansible.builtin.dnf:
        name: "{{ db_packages }}"
        state: present
      when: ansible_distribution == "CentOS"
